### ISSUE TITLE
Amidon hangs after displaying "Login to Mastodon" dialog

### ISSUE THREAD

**Issue by kevbrice** [BlitterStudio/amidon#5] opened 2023-04-09 08:49 UTC
To repro:

1. Get Amiga Forever
2. Start the Workbench 3.X image
3. Copy TextEditor.mcc, BetterString.mcc, HTMLview.mcc , and codesets.library to the correct locations
4. Upgrade MUI to [3.9](https://github.com/amiga-mui/muidev/releases/tag/MUI-3.9-2015R1)
5. Install AmiSSL 4.12
6. Launch Amidon 1.1
7. Enter "mastodon.social" as the server URL, then click "Login"

EXPECTED
A functional dialog, where buttons respond to clicks

ACTUAL
The entire dialog renders, but the application then immediately locks up. I can type in the textbox but buttons in the view don't reflect pressed state and don't do anything in response to being clicked. Clicking the "Close" and "Iconify" gadgets in the title bar reflects pressed state, but then does nothing. Anything invalidating the dialog's visuals, like resizing, causes that part of the dialog to be blank.

NOTES
- I have the same problem on real hardware running AmigaOS 3.2.2 and MUI [5.0-20210831](https://github.com/amiga-mui/muidev/releases/tag/MUI-5.0-20210831)
- I also have AmiSSL 5.8 installed. I understand Amidon doesn't use AmiSSL 5, but installing AmiSSL 5 updates the shared certificates also used by AmiSSL 4, so it's worth noting.

![image](https://user-images.githubusercontent.com/48140644/230763298-1f03c617-c5e9-4721-af29-fc7ba53e621a.png)

**Comment by ProbDenis** [comment] 2023-05-13 08:28
I'm getting the same error on a real A1200 with an accelerator (68LC060, 128 MB fast ram), using AmigaOS 3.2.2 and MUI 3.9. It freezes when the login dialog appears.

**Comment by midwan** [comment] 2023-05-13 10:40
Please test with v1.2 which was just released - it includes support for the latest AmiSSL now, just in case this was related to that.

**Comment by ProbDenis** [comment] 2023-05-15 07:30
Just tested with Amidon 1.2, but it's still freezing.

**Comment by kevbrice** [comment] 2023-05-23 06:07
@midwan Yeah, 1.2 doesn't fix this at all - it still hangs in the same spot, including in Amiga Forever. Given this breaks on a real Amiga with a basically-stock installation and in the stock Amiga Forever 3.x configuration, is there something special about your development machine? Would it be possible to develop against a clean installation so accidental dependencies don't keep sneaking in?

**Comment by midwan** [comment] 2023-05-23 06:15
> @midwan Yeah, 1.2 doesn't fix this at all - it still hangs in the same spot, including in Amiga Forever. Given this breaks on a real Amiga with a basically-stock installation and in the stock Amiga Forever 3.x configuration, is there something special about your development machine? Would it be possible to develop against a clean installation so accidental dependencies don't keep sneaking in?

I don't think there's anything special here, at least nothing I could find so far. My tests were done in clean installations of AmigaOS 3.1 and 3.2.2.1, both on real hardware and on emulated environments. I could only recreate this in the Amiga Forever environment, nowhere else (so far).

Given that it also works for most people, according to what they've reported to me, it must be some combination of things we haven't isolated yet that trigger this.

**Comment by midwan** [comment] 2023-05-27 18:52
Tried the following steps in a new environment:
- A1200 config, 020 + JIT, 32MB Fast (WinUAE)
- Kickstart 47.111 - A1200 (OS 3.2.2)
- Installed AmigaOS 3.2
- Upgraded to 3.2.2.1
- Installed P96 2.1b, using `uaegfx` driver
- Installed MUI 5.0
- Installed HTMLview, BetterString and TextEditor MUI classes
- Installed AmiSSL 5.8
- Installed the latest Amidon binary

Then I tried the same steps as mentioned above, namely use `mastodon.social` in the Settings window, then click on `Login`.

I can still not recreate the problem.

Perhaps you can find something you may have different in your case, based on my steps above?

**Comment by kevbrice** [comment] 2023-05-27 18:57
@midwan I'll have to experiment more. Offhand, my actual machine has a 68060 with mmulib enabled.

**Comment by midwan** [comment] 2023-07-06 12:48
@kevbrice 
Based on feedback I got from another user who got the same issue recently, and managed to find a workaround: 
- Do you have P96 installed?
- If not, can you install it and check if it makes a difference?
- If yes, which version?

This seems like some kind of bug between Hollywood and the existence or not of (perhaps a specific version) P96.

**Comment by kevbrice** [comment] 2023-07-06 18:04
No, I don't have P96 installed, as my machine doesn't have an RTG card. I'd rather not install it since it would serve no purpose on my machine. Amiga Forever comes with a much older, free version of P96. I could try installing the latest there, but it seems like a problem if Amidon secretly depends on P96. 🙂

**Comment by kevbrice** [comment] 2023-07-07 19:22
@midwan I don't know anything about Amiga software development, so is there some way to break into the process and get a call stack for when the application is hung to narrow down the bug? Whether the bug is in Hollywood or Amidon, it's a bad bug if things only work with IComp versions of P96, not even with native Amiga graphics.

**Comment by midwan** [comment] 2023-07-07 20:32
Unfortunately I can't get a stack trace from it, I only know what the code did just before it's triggered and it doesn't seem to matter. This seems like some weird Hollywood bug, so I'll report it as such upstream.

The Aminet P96 version (2.1b) seems to work, at least in my tests here. But changing the screenmode to a PAL:HighRes Laced and doing the exact same thing, triggered the problem. It might be a combination of things that trigger it, but in any case it seems to be caused by Hollywood itself.

**Comment by midwan** [comment] 2023-07-07 20:37
@kevbrice Opened an issue on the Hollywood forums: https://forums.hollywood-mal.com/viewtopic.php?t=3762

**Comment by RetroSwimAU** [comment] 2023-10-02 10:53
The reply on that forum post isn't promising 😅

I've also experienced this exact issue on my real hardware:

A1200 w/ 68030 @ 50MHz and 128MB RAM
AmigaOS 3.2
Exact versions of MUI, AmiSSL etc shown in documentation

Is there a way to poke the values into the config files manually and avoid using the setup wizard? I attempted this but couldn't quite reverse engineer what the Configs should look like haha

**Comment by midwan** [comment] 2023-10-12 15:56
Unfortunately this seems out of my hands, as it's something inside Hollywood itself. 
I think there was a P96 driver for native (AGA) chipsets on Aminet, that might help if installed (haven't tested it personally, can't guarantee it will). It's worth a try at least.

**Comment by kevbrice** [comment] 2023-11-08 03:37
@midwan That's a shame. I would note that the same bug happens with the version of P96 loaded with 3.x in Amiga Forever.

**Comment by midwan** [comment] 2023-11-08 07:42
After further experiments, it seems that there might be a workaround, even if it's not ideal:
If I use the Plananarama plugin and compile the app with it, then it works on native chipsets (AGA) - but it crashes on RTG. But that means I could produce separate binaries, one for RTG and one for AGA, and perhaps that's helpful for the people that can't get it to work.

**Comment by midwan** [comment] 2023-12-03 19:06
Fixed with v1.3 release

**Closed by midwan** 2023-12-03 19:06 UTC
Labels: bug
